[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

lib_deps =
    tanakamasayuki/TensorFlowLite_ESP32 @ ^1.0.0
    hideakitai/MPU9250 @ ^0.4.8
    knolleary/PubSubClient @ ^2.8